# @name loginAPI
POST http://localhost:8081/api/v1/auth/signin
content-type: application/json

{
    "user": "admin",
    "senha": "senha"
}

###

@token = {{loginAPI.response.body.* 7}}

###
GET http://localhost:8081/api/v1/pacientes
Authorization: Bearer {{token}}

###
GET http://localhost:8081/api/v1/pacientes/65
Authorization: Bearer {{token}}

###
GET http://localhost:8081/api/v1/pacientes/?nome=ze
Authorization: Bearer {{token}}

###

POST http://localhost:8081/api/v1/pacientes
Authorization: Bearer {{token}}
content-type: application/json

{
    "nome": "Zezinho",
    "sexo": "Masculino",
    "dataNascimento": "2022-08-17T00:00:00"
}

###

POST http://localhost:8081/api/v1/pacientes
Authorization: Bearer {{token}}
content-type: application/json

{
    "id" : 1,
    "nome": "Zezinho",
    "sexo": "Masculino",
    "dataNascimento": "2022-08-17T00:00:00"
}

###

POST http://localhost:8081/api/v1/pacientes
Authorization: Bearer {{token}}
content-type: application/json

{
    "nome": "Mariazinha",
    "sexo": "Feminino",
    "dataNascimento": "2022-08-16T00:00:00"
}


###

PUT http://localhost:8081/api/v1/pacientes/65
Authorization: Bearer {{token}}
content-type: application/json

{
    "nome": "Zezinho da Silva Sauro",
    "sexo": "Masculino",
    "dataNascimento": "2022-08-17T00:00:00"
}

###

DELETE http://localhost:8081/api/v1/pacientes/33
Authorization: Bearer {{token}}


// MEDICO


###
GET http://localhost:8081/api/v1/medicos
Authorization: Bearer {{token}}

###
GET http://localhost:8081/api/v1/medicos/65
Authorization: Bearer {{token}}

###
GET http://localhost:8081/api/v1/medicos/?nome=ze
Authorization: Bearer {{token}}

###

POST http://localhost:8081/api/v1/medicos
Authorization: Bearer {{token}}
content-type: application/json

{
    "nome": "Zezinho",
    "crm": "1234"
}

###

PUT http://localhost:8081/api/v1/medicos/65
Authorization: Bearer {{token}}
content-type: application/json

{
    "nome": "Zezinho da Silva Sauro",
    "crm": "4321"
}

###

DELETE http://localhost:8081/api/v1/medicos/33
Authorization: Bearer {{token}}

// CIDADE


###
GET http://localhost:8081/api/v1/cidades
Authorization: Bearer {{token}}

###
GET http://localhost:8081/api/v1/cidades/65
Authorization: Bearer {{token}}

###
GET http://localhost:8081/api/v1/cidades/?nome=jo
Authorization: Bearer {{token}}

###

POST http://localhost:8081/api/v1/cidades
Authorization: Bearer {{token}}
content-type: application/json

{
    "nome": "Joinville"
}

###

PUT http://localhost:8081/api/v1/cidades/65
Authorization: Bearer {{token}}
content-type: application/json

{
    "nome": "Joinvas"
}

###

DELETE http://localhost:8081/api/v1/cidades/33
Authorization: Bearer {{token}}

###
GET http://localhost:8081/api/v1/consultas
Authorization: Bearer {{token}}

###

POST http://localhost:8081/api/v1/consultas
Authorization: Bearer {{token}}
content-type: application/json

{
    "data": "2002-09-09",
    "status": "Solteira"
}